#!/bin/bash

if [ ! -d libevent-2.0.10-stable ] ; then


wget http://monkey.org/~provos/libevent-2.0.10-stable.tar.gz
tar zxvf libevent-2.0.10-stable.tar.gz
cd libevent-2.0.10-stable
./configure
make
cd ../

fi
make
